#!/bin/sh
#
# @name Scaner1
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @maintainer Maciej Podsędkowski <mpodsedkowski@gmail.com>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.08
	param set MC_PITCHRATE_I 0.02
	param set MC_PITCHRATE_D 0.001
	
	param set MC_ROLLRATE_P 0.08
	param set MC_ROLLRATE_I 0.01
	param set MC_ROLLRATE_D 0.0005
	
	param set MC_YAWRATE_P 0.15
	param set MC_YAWRATE_I 0.1
	param set MC_YAWRATE_D 0
	
	param set PWM_RATE 400
	param set DSHOT_CONFIG 1200
	
fi

set MIXER quad_x

set PWM_OUT 1234
